from pathlib import Path
from html import escape
import json, shutil, re, os
ROOT=Path(__file__).resolve().parent
OUT=ROOT/'dist'
OUT.mkdir(exist_ok=True)
shutil.copytree(ROOT/'assets',OUT/'assets',dirs_exist_ok=True)
for f in ['style.css','site.js']: shutil.copy(ROOT/'src'/f,OUT/f)
APP='https://app.talent-share.com/'
ORIGIN=os.environ.get('SITE_ORIGIN','https://talentshare-editorial.sarpower.chatgpt.site').rstrip('/')
PRODUCTION=os.environ.get('PRODUCTION','0')=='1'
BASE=os.environ.get('BASE_PATH','').strip('/')
def u(path):
 if not path.startswith('/') or not BASE: return path
 return f'/{BASE}/' if path=='/' else f'/{BASE}{path}'
pages=[]
A='<span class="arrow" aria-hidden="true">↗</span>'
def btn(text,url,style='purple'):return f'<a class="btn {style}" href="{url}">{text}{A}</a>'
def link(text,url):return f'<a class="textlink" href="{url}">{text}{A}</a>'
def img(name,alt,cls='',eager=False):return f'<img src="{u("/assets/"+name+".jpg")}" alt="{escape(alt)}" class="{cls}" loading="{"eager" if eager else "lazy"}" decoding="async">'
def eyebrow(text):return f'<div class="eyebrow">{text}</div>'
def head(kicker,title,desc='',action=''):return f'<div class="section-head"><div>{eyebrow(kicker)}<h2>{title}</h2></div>{action or ("<p>"+desc+"</p>" if desc else "")}</div>'
def section(content,cls=''):return f'<section class="{cls}"><div class="wrap">{content}</div></section>'
def faq(items):return ''.join(f'<details data-faq><summary>{q}</summary><p>{a}</p></details>' for q,a in items)
def hero(kicker,title,desc,photo=None,alt='',action='',breadcrumb=''):
 text=f'{eyebrow(kicker)}<h1>{title}</h1><p class="lead">{desc}</p>'+ (f'<div class="actions">{action}</div>' if action else '')
 if photo:text=f'<div class="split"><div>{text}</div>{img(photo,alt,"image-block",True)}</div>'
 return f'<section class="page-hero"><div class="wrap"><div class="breadcrumb"><a href="{u("/")}">Home</a><span>/</span>{breadcrumb or kicker}</div>{text}</div></section>'
def closing():return f'<section class="closing"><div class="star-small" aria-hidden="true">✳</div><h2>Find a program<br><span class="serif">you want to join.</span></h2><p>Check the provider, level, and schedule before you book. You can explore public program pages without an account.</p><div class="actions">{btn("Explore programs",APP)}{link("Become a provider",APP+"login")}</div></section>'
def terminology(value):
 replacements={'TalentShare':'talent-share','TALENTSHARE':'talent-share','Talent Share':'talent-share','Teachers':'Providers','teachers':'providers','Teacher':'Provider','teacher':'provider','Learners':'Seekers','learners':'seekers','Learner':'Seeker','learner':'seeker','Students':'Seekers','students':'seekers','Student':'Seeker','student':'seeker','Courses':'Programs','courses':'programs','Course':'Program','course':'program','Classes':'Programs','classes':'programs','Class':'Program','class':'program','classmates':'fellow seekers'}
 for old,new in replacements.items(): value=re.sub(r'\b'+re.escape(old)+r'\b',new,value)
 return value

def copy_html(html):
 chunks=re.split(r'(<[^>]+>)',html)
 for i,chunk in enumerate(chunks):
  if not chunk.startswith('<'): chunks[i]=terminology(chunk)
  else: chunks[i]=re.sub(r'((?:alt|aria-label|content)="|(?:alt|aria-label|content)=\')(.*?)(["\'])',lambda m:m.group(1)+terminology(m.group(2))+m.group(3),chunk)
 return ''.join(chunks)

def page(slug,title,desc,keyword,content):
 title,desc,keyword=map(terminology,(title,desc,keyword))
 content=copy_html(content)
 path=OUT/slug.strip('/') if slug!='/' else OUT
 path.mkdir(parents=True,exist_ok=True)
 nav=''.join(f'<a href="{u(href)}"'+(' aria-current="page"' if slug==href else '')+f'>{t}</a>' for t,href in [('Explore subjects','/subjects/'),('How it works','/how-it-works/'),('The experience','/learning-experience/'),('For providers','/teach/')])
 html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)}</title><meta name="description" content="{escape(desc,quote=True)}"><meta name="robots" content="{'index,follow' if PRODUCTION else 'noindex,nofollow'}"><link rel="canonical" href="{ORIGIN}{slug}"><meta property="og:type" content="website"><meta property="og:title" content="{escape(title,quote=True)}"><meta property="og:description" content="{escape(desc,quote=True)}"><meta property="og:url" content="{ORIGIN}{slug}"><meta name="theme-color" content="#291449"><link rel="icon" type="image/svg+xml" href="{u("/favicon.svg")}"><link rel="stylesheet" href="{u("/style.css")}"><script src="{u("/site.js")}" defer></script></head><body><a class="skip" href="#main">Skip to content</a><div class="topline">REAL PEOPLE <span>✳</span> LIVE LEARNING <span>✳</span> ONLINE & IN PERSON</div><header><div class="nav wrap"><a href="{u("/")}" class="logo" aria-label="TalentShare home"><span class="brand-symbol"><img src="{u("/assets/logo.png")}" alt="" width="172" height="57"></span><span class="wordmark">talent-share</span></a><nav class="navlinks" id="navigation" aria-label="Main navigation">{nav}</nav><div class="nav-actions"><a class="signin" href="{APP}login">Sign in</a>{btn('Explore programs',APP,'small')}</div><button class="menu" aria-expanded="false" aria-controls="navigation">Menu</button></div></header><main id="main">{content}</main><footer><div class="wrap"><div class="foot-grid"><div class="foot-brand"><a href="{u("/")}" class="footer-logo" aria-label="talent-share home"><span class="brand-symbol"><img src="{u("/assets/logo.png")}" alt="" width="172" height="57" loading="lazy"></span><span class="wordmark">talent-share</span></a><p>Learn from teachers in live online and in-person programs.</p></div><div class="foot-links"><strong>Learning</strong><a href="{u("/subjects/")}">Explore subjects</a><a href="{u("/how-it-works/")}">How it works</a><a href="{u("/learning-experience/")}">The learning experience</a><a href="{APP}">Browse programs ↗</a></div><div class="foot-links"><strong>Teaching</strong><a href="{u("/teach/")}">Teach on TalentShare</a><a href="{APP}login">Become a provider ↗</a><a href="{u("/about/")}">About TalentShare</a><a href="{u("/trust/")}">Booking with confidence</a></div><div class="foot-links"><strong>Help & support</strong><a href="{u("/faq/")}">Questions & answers</a><a href="mailto:support@talent-share.com">Contact support ↗</a><a href="https://www.talent-share.com/legal">Legal & privacy ↗</a><a href="{APP}login">Sign in ↗</a></div></div><div class="foot-bottom"><span>© 2026 TalentShare. All rights reserved.</span><span>Live classes, online and in person.</span></div></div></footer></body></html>'''
 (path/'index.html').write_text(copy_html(html))
 pages.append(dict(path=slug,title=title,description=desc,primary_keyword=keyword,html=content))

FAQ=[
('What is TalentShare?', 'TalentShare is a marketplace for live learning. You can find a program, read about the teacher, book a date, and attend online inside the app or in person. The same account can be used to learn and, after an approved application, to teach.'),
('Are these live classes or recorded videos?', 'Programs are taught live, either online or in person. Online sessions run in TalentShare’s video room, with camera, microphone, screen sharing, and session chat. Teachers may also share supporting resources, including videos, in the program’s file library.'),
('Do I need an account to look at a program?', 'You can read public program pages before signing in. Booking requires an account. The classroom, course files, announcements, and class discussion are available to confirmed learners and the teacher.'),
('How do I know whether a class is right for me?', 'Check its level, learning outcomes, requirements, materials, delivery mode, and full schedule. Read the teacher’s profile and any reviews available. You can also message the teacher from the program if you need to clarify something before booking.'),
('How much does a program cost?', 'Each teacher sets the program price. Checkout shows the program price and service fee separately, along with the total, before you pay. Your receipt uses the same breakdown. Check the selected program for its current price.'),
('Can I book just one date in a repeating program?', 'When a program is offered on several start dates, you book the date selected in the booking card. Check the full schedule for that selection: a single booking may include multiple sessions. Other start dates are separate bookings.'),
('Where do I join an online class?', 'Sign in and open your program’s schedule. Confirmed learners can join from 15 minutes before the session starts. The video room is inside TalentShare, so you do not need a separate meeting app.'),
('What happens between sessions?', 'You can read teacher announcements, join the class discussion, send private program-linked messages, and download resources the teacher has shared. Those conversations and files stay with the program.'),
('How are teachers reviewed?', 'People applying to teach submit a profile with information such as their experience, education, skills, languages, and relevant links. TalentShare reviews the application before approval. Read the public profile to assess whether a teacher’s background fits what you want to learn.'),
('Who can leave a review?', 'A learner with a completed enrollment can leave a rating and written review. Teachers can reply publicly. Reviews appear with the program and teacher, helping you understand the experiences people chose to share.'),
('Can I cancel a booking?', 'You can request a cancellation within 24 hours of enrolling if the first session is still at least 24 hours away. Requests are subject to platform approval. Check the current policy in the app before booking and contact support if you need help.'),
('Can I teach and learn with the same account?', 'Yes. You can learn with your account and apply to become a teacher from it. After approval, your teaching and learning activity have their own dashboard views under the same login.'),
('What do I need to apply to teach?', 'Prepare a profile photo, bio, professional background, skills, and the talents you want to share. Add relevant education, certifications, teaching experience, languages, and links. The application shows required information that is missing before you submit it for review.'),
('Can I create a program without using AI?', 'Yes. You can fill in the program details yourself. If you use the writing assistant, start with a short description of your idea, then check and edit the suggested listing before publishing. You choose the final content, schedule, price, and capacity.'),
('How do teachers manage their programs?', 'The teacher dashboard brings together drafts and published programs, student lists, the teaching calendar, program messages, and reports. Teachers can see enrollment and earnings information and export reports for a selected date range.'),
('Can I use TalentShare on my phone?', 'TalentShare has a responsive website for phones, tablets, and computers. You can open the app in your browser to browse programs, manage your account, and access your enrolled programs. Use a device and connection suited to the session you are attending.')]

SUBJECTS=[
 dict(slug='arts-and-crafts',name='Arts & crafts',image='pottery',alt='Hands guiding wet clay on a pottery wheel',group='creative',tag='Make something with your hands',h1='Live art classes and craft workshops',intro='Explore drawing, painting, pottery, and other crafts. Compare the techniques, materials, and experience needed before choosing a class.',body=[('Choose the thing you want to make','Start with the material or technique that interests you: drawing, painting, pottery, calligraphy, or another craft. Then look at the actual outcomes. A class about drawing faces asks something different of you than a general introduction to sketching. A useful listing tells you what you will practise and what experience you need.'),('Choose online or in person','An online class can let you work at your own table while watching a live demonstration. An in-person workshop may make more sense when the work calls for studio equipment or close physical guidance. Check the location, tools, and materials before choosing. Do not assume that supplies, firing, or finishing services are included unless the program says so.'),('Leave space for practice','A single workshop gives you a focused introduction. A course or lesson series can give you more time between sessions to try a technique again. Read the full schedule and think about when you will practise. If your teacher shares course files or invites discussion, use those spaces to keep your questions connected to the class.'),('Look closely at the teacher’s work','The portfolio is a useful place to start. Notice the materials, style, and type of work the teacher shares, then read their background and the program requirements. If you are new, look for a beginner level and an explanation of what to bring. Ask about anything that would change your decision before you book.')],check=['The technique and level','Supplies you need to bring','Studio access or equipment','What the sessions cover'],questions=[('Do I need to buy art supplies first?','Read the materials list before buying anything. The teacher should explain what you need and whether any supplies are included. If a tool or material is unclear, ask about the specific program.'),('Can I learn a hands-on skill online?','Some techniques work well through live demonstrations and practice at home. Others depend on equipment or a physical workspace. Choose the delivery mode that fits the skill and the materials available to you.')]),
 dict(slug='technology-and-digital-skills',name='Technology & digital skills',image='code',alt='Two people working through a task on a laptop',group='professional',tag='Software, data, and digital tools',h1='Live technology classes and digital skills training',intro='When a tutorial stops matching your screen, it helps to have someone to ask. Live learning gives you a place to work through the step you missed and understand why it matters.',body=[('Start with a task you want to handle','A useful goal might be building your first small program, understanding a data workflow, or getting comfortable with a tool used at work. Name that task before comparing courses. Broad subject labels such as AI or software cover very different levels of depth, so the learning outcomes should do more of the explaining.'),('Check the setup before the first session','Look for the software, accounts, hardware, and prior knowledge a program requires. A beginner label does not always mean you can arrive without any preparation. If the listing asks for a development environment or a paid tool, work out what you will need before booking. Ask the teacher if the requirements are not clear.'),('Pick a format that matches your question','A workshop can focus on one workflow. A course or boot camp can spread the subject across several sessions. A consultation may suit a specific question you want to discuss with a teacher. Read the schedule as carefully as the description so that the time commitment fits your week.'),('Use the room to understand the process','In an online program, the teacher can share a screen and you can ask questions in the session chat. Shared files can keep examples and supporting resources with the class. After a session, the discussion gives enrolled learners a place to continue a question without losing it in a separate email thread.')],check=['Tools and account requirements','Expected starting knowledge','Practice time between sessions','The specific skills covered'],questions=[('Does every program include software?','Do not assume that software or paid accounts are included. Check the requirements and materials for the program you are considering.'),('Will a class qualify me for a job?','Learning outcomes describe what a program teaches. They are not a promise of employment or professional certification. Read the details and choose a program for the skills you want to develop.')]),
 dict(slug='food-and-cooking',name='Food & cooking',image='cooking',alt='A kitchen worktop ready with ingredients and cooking tools',group='everyday',tag='Cooking techniques and cuisines',h1='Live cooking classes and culinary workshops',intro='Learn cooking techniques with a teacher you can ask questions. Choose a class based on the dishes you want to make, your experience, and the equipment you have.',body=[('Choose a useful starting point','You might want to understand a cuisine, practise a specific technique, or feel more comfortable preparing a complete meal. Read the outcomes rather than relying on an appealing dish name. Check whether you will cook along, watch a demonstration, or take part in another kind of session.'),('Think about where you will cook','For a live online program, compare the equipment and ingredients with what you have at home. For an in-person workshop, check the venue details and what you are expected to bring. A class that fits your kitchen and your experience is easier to prepare for than one that assumes tools you have never used.'),('Ask about ingredients before booking','Look for an ingredient or materials list and raise questions about substitutions, dietary needs, or allergies directly with the teacher. The description may not cover every individual requirement. Get the information you need before deciding whether a program is suitable.'),('Make the practice part realistic','A short workshop can introduce a dish or technique. A course may give you several sessions to build on it. Check the schedule, preparation time, and any work expected between classes. Afterward, use shared resources where the teacher provides them and keep follow-up questions with the program discussion.')],check=['Ingredients and equipment','Cook-along or demonstration','Dietary questions to ask','Preparation before class'],questions=[('Are ingredients included?','That depends on the program. Read its materials and requirements, and ask the teacher if ingredient costs or preparation are not explained.'),('Can a teacher adapt recipes for me?','Ask before booking. Substitutions and dietary accommodations depend on the recipe, format, and teacher. Do not assume that a class can meet a specific dietary need.')]),
 dict(slug='music-and-performance',name='Music & performance',image='music',alt='Microphone set up for a live performance',group='creative',tag='Music, acting, and performance',h1='Live music lessons and performance classes',intro='Find a lesson that matches your experience and the skill you want to practise. Check the equipment, preparation, and schedule before booking.',body=[('Get specific about what you want to practise','Music theory, songwriting, an instrument, acting, and speaking on stage ask for different kinds of practice. Decide what you want to work on first. Then read the program outcomes and level. A focused goal makes it easier to tell whether a broad course or a short lesson is the right fit.'),('Read the teacher’s background and portfolio','A teacher’s profile brings together their experience, skills, languages, and work they have chosen to share. Where a portfolio includes audio or video, use it to understand their approach and area of practice. A familiar style can be helpful, but the program description still needs to explain what you will learn.'),('Prepare the space as well as the equipment','Check whether you need an instrument, written material, or particular equipment. For live online sessions, think about a space where you can hear and participate clearly. In-person programs have their own venue and material requirements. Ask about anything that could affect your ability to take part.'),('Plan your practice time','A single session may suit a specific question. A series can leave room for practice between meetings. Look at every session in the schedule and plan around the work you can realistically do. The class discussion and private messages provide separate ways to ask a follow-up question where appropriate.')],check=['The skill and starting level','Instrument or equipment needs','Your practice schedule','Teacher portfolio and language'],questions=[('Can I join as a complete beginner?','Choose a program marked beginner and read its requirements. Some programs may still expect an instrument or basic preparation.'),('Should I book one lesson or a series?','Choose based on the program outcomes and the time you can commit to practice. Check the full schedule to understand exactly what the selected booking includes.')]),
 dict(slug='movement-and-wellbeing',name='Movement & wellbeing',image='yoga',alt='People practising yoga together in a studio',group='everyday',tag='Movement, fitness, and wellbeing',h1='Live movement classes and wellbeing programs',intro='Compare movement and wellbeing programs by level, requirements, and teaching approach. Choose a schedule that fits your week.',body=[('Begin with the activity and the level','Movement, yoga, fitness, and related subjects can vary widely in pace and physical demands. Read the description and requirements carefully. Look for concrete information about what the sessions involve instead of choosing from a broad promise about how you will feel afterward.'),('Choose a setting where you can participate','For an online session, check the space and equipment needed and whether you can follow the teacher comfortably on your device. For an in-person program, review the venue details and travel time. The right setting depends on the activity and your own circumstances.'),('Ask the questions that affect your decision','If a requirement is unclear, message the teacher about the program before booking. Describe the practical question you need answered, such as equipment, pace, or expected experience. A program description is not a personal assessment, and participation should fit your individual needs.'),('Read the schedule beyond the first date','Check whether you are choosing a single session or a program with several meetings. The schedule lists those sessions together. Think about the time you can set aside consistently and any preparation the teacher requests. Announcements and reminders help you stay informed if the program changes.')],check=['Level and physical requirements','Space and equipment','Venue or online setup','The full session schedule'],questions=[('Does beginner mean suitable for everyone?','No. A level describes the program’s intended starting point. Read its requirements and ask the teacher about the activity before deciding whether it fits your needs.'),('Is equipment provided?','Check the materials and venue information. Online and in-person programs may have different expectations, and equipment should not be assumed to be included.')]),
 dict(slug='business-and-communication',name='Business & communication',image='people',alt='A group collaborating around a table',group='professional',tag='Business and communication skills',h1='Live business classes and communication coaching',intro='You may have a presentation coming up, a team conversation to prepare for, or a business idea you want to examine. Start with that situation, then find a program that addresses it.',body=[('Bring a concrete question','Leadership, business, and communication cover a lot of ground. Think about the task you want to improve: structuring a presentation, explaining an idea, or practising a particular communication skill. Compare that task with the stated outcomes, rather than choosing only from a broad program title.'),('Choose between a group and a focused conversation','A class or workshop can offer a shared learning structure. Coaching, mentoring, or a consultation may be organised around a more focused topic. Do not infer the group size or level of personal attention from the format name alone. Read the program details and ask when something is unclear.'),('Read experience in context','Check the teacher’s background, skills, current role, and portfolio where available. Look for experience connected to the subject you want to discuss. Reviews from completed enrollments can add context, but a rating alone does not explain whether the program suits your particular situation.'),('Look for specific learning outcomes','Look for outcomes you can recognise and practise. Review any preparation, materials, and session dates before paying. After enrollment, private messages give you a program-linked place for individual questions, while class discussion keeps group questions together. Use the right space for what you want to share.')],check=['Your specific learning goal','Format and group size','Relevant teacher experience','Any preparation required'],questions=[('Are consultations always one-to-one?','Check the individual program. Its capacity, description, and schedule should tell you how the session is organised.'),('Can I discuss a private question with the teacher?','TalentShare supports private, program-linked messages. Use those for individual questions, and clarify the scope of a consultation or coaching program before booking.')])]

def category_cards():
 return '<div class="categories">'+''.join(f'<a class="category" data-group="{s["group"]}" href="{u("/subjects/"+s["slug"]+"/")}"><div class="cat-photo">{img(s["image"],s["alt"])}</div><div class="category-body"><h3>{s["name"]}{A}</h3><p>{s["tag"]}</p><span class="tagline">Read the subject guide</span></div></a>' for s in SUBJECTS)+'</div>'
def classroom():return f'''<div class="product-window"><div class="window-bar"><span class="traffic" aria-hidden="true"><i></i><i></i><i></i></span><span>Your talent-share session</span><span>↗</span></div><div class="video">{img('code','A teacher and learner working through something on a laptop')}<span class="live-pill"><i class="dot"></i> LIVE SESSION</span><span class="video-label">Live video with screen sharing</span></div><div class="video-tools" aria-label="Illustrated classroom controls"><span>♩</span><span>▣</span><span>↥</span><span>☰</span><span class="red">Leave</span></div><div class="demo-bottom"><span>Video · Screen share · Session chat</span><span class="demo-tag">Illustration</span></div></div>'''
def comms():
 tabdata=[('announcements','01','Announcements','The teacher’s official updates'),('discussion','02','Class discussion','The conversation between sessions'),('messages','03','Private messages','A question just for your teacher'),('live','04','Live session chat','For the moment you are in')]
 tabs=''.join(f'<button class="tab" role="tab" id="tab-{k}" data-chat="{k}" aria-selected="{str(i==0).lower()}" aria-controls="chat-panel" tabindex="{0 if i==0 else -1}"><span>{n}</span><span><strong>{title}</strong><small>{sub}</small></span><span aria-hidden="true">↗</span></button>' for i,(k,n,title,sub) in enumerate(tabdata))
 return f'''<div class="comms-grid"><div>{eyebrow('Questions and updates')}<h2>A follow-up question?<br><span class="serif">Keep it with the program.</span></h2><div class="tabs" role="tablist" aria-label="Ways to communicate" aria-orientation="vertical">{tabs}</div></div><div><div class="chat-demo" id="chat-panel" role="tabpanel" aria-labelledby="tab-announcements" tabindex="0"><div class="chat-header"><span class="avatar">P</span><div><strong>Announcements</strong><small>From your teacher · For the whole class</small></div></div><div class="bubble"><span class="pin">Pinned announcement</span><strong>Before our next session</strong><p>Bring your practice work. We’ll look at it together before starting the next exercise.</p></div><div class="chat-hint">✓ &nbsp; Official updates arrive in the app and by email.</div><p class="comms-copy">Only the teacher posts here. Pinned updates stay at the top, and announcements have their own unread count.</p></div><p class="chat-hint">Interactive feature illustration. Example messages.</p></div></div>'''
def steps():return '<div class="steps">'+''.join(f'<div class="step"><span class="number">0{i}</span><h3>{h}</h3><p>{p}</p></div>' for i,(h,p) in enumerate([('Find a program','Browse programs in the app. Narrow your search by subject, level, price, and online or in person.'),('Read the details','Meet the teacher, check the outcomes and materials, and choose the date that works for you.'),('Book your place','See the program price, service fee, and total before paying. Your receipt keeps the same breakdown.'),('Attend your class','Join from your program page or head to the venue. Your schedule, files, and class conversations stay together.')],1))+'</div>'

home=f'''<div class="wrap"><div class="hero"><div class="reveal">{eyebrow('A marketplace for live learning')}<h1>Find a program.<br>Learn with someone<br><span class="serif">you can ask.</span></h1><p class="lead">Learn a skill with a provider who can explain it, demonstrate it, and answer your questions. Explore live programs online or in person.</p><div class="actions">{btn('Explore programs',APP)}{link('Find your subject','#subjects')}</div><p class="small-note">Browse program details before creating an account.</p></div><div class="hero-art reveal">{img('pottery','Hands guiding clay into shape on a pottery wheel','hero-image',True)}<div class="star" aria-hidden="true">✳</div><div class="side-note">Live online<br>or in person</div><div class="float-note"><strong>“Can you show that again?”</strong><small>A question you can ask during the session.</small></div><span class="photo-caption">Illustrative learning photo.</span></div></div></div><div class="feature-strip"><div class="wrap"><span><i>◉</i> Learn live with a provider</span><span><i>↗</i> Choose a program at your level</span><span><i>▤</i> Check the details before booking</span></div></div>'''
home+=section(head('Sound familiar?','You want to learn.<br>But you still have questions.',desc='Finding content is easy. Finding the right help can take more work.')+'''<div class="problem-grid"><article><span class="problem-number">01</span><h3>You get stuck watching a video.</h3><p>You replay the same part, but it does not explain the step you missed. You want to ask someone to show it another way.</p></article><article><span class="problem-number">02</span><h3>You are unsure which program fits.</h3><p>A title sounds interesting, but you need to know the level, what you will practise, and whether you have the right experience.</p></article><article><span class="problem-number">03</span><h3>You want to know who is teaching.</h3><p>Before paying, you want to read about the provider’s background and see whether their experience is relevant to you.</p></article></div>''','wash')
home+=section(f'<div class="split"><div class="image-wrap">{img("workshop","People learning a practical skill together","image-block")}<span class="image-label">Watch a demonstration. Ask a question. Try it yourself.</span></div><div>{eyebrow("Why learn live?")}<h2>Get an explanation<br><span class="serif">when you need one.</span></h2><p>In a live program, you can ask your provider about the part you do not understand. That conversation can help you work out what to try next.</p><p>talent-share brings people who want to learn, called <strong>seekers</strong>, together with people who teach, called <strong>providers</strong>. Choose a program based on your interests, experience, and the time you can commit.</p><div class="actions">{link("See what a program experience includes",u("/learning-experience/"))}</div></div></div>')
home+=section('<div id="subjects">'+head('Start with what you want to learn','Which subject interests you?',desc='Use these guides to work out what to look for. Current programs and dates are in the app.')+category_cards()+f'<div class="actions">{btn("Browse current programs",APP)}{link("View all subject guides",u("/subjects/"))}</div></div>')
home+=section(head('Choose with the details in front of you','Know who you will learn from.<br>Know what you are booking.',desc='A useful program page helps you answer the questions that matter before you pay.')+'''<div class="decision-grid"><div class="decision-visual"><span class="mini-label">Before you choose a program</span><h3>Does this fit what I need?</h3><div class="decision-row"><span>01</span><div><strong>The provider</strong><p>Background, skills, portfolio, and available reviews</p></div></div><div class="decision-row"><span>02</span><div><strong>The learning</strong><p>Level, outcomes, requirements, and materials</p></div></div><div class="decision-row"><span>03</span><div><strong>The commitment</strong><p>Selected date, full schedule, location, and checkout total</p></div></div></div><div class="decision-copy"><h3>Read about the provider</h3><p>Provider applications are reviewed. Explore their profile and work, then read available reviews from seekers who completed a program.</p><h3>Choose the right starting point</h3><p>Check what you will learn and what you need to bring. If a requirement is unclear, message the provider from the program before booking.</p><h3>See the full commitment</h3><p>Look at every included session, not only the first date. Checkout shows the program price and service fee separately before you pay.</p>'''+link('More about booking and payments',u('/trust/'))+'</div></div>','wash')
home+=section(f'<div class="split"><div>{eyebrow("What happens after you book")}<h2>Spend your time learning,<br><span class="serif">with the details organised.</span></h2><p>Your program page keeps the session schedule, shared resources, and conversations together. For online programs, it is also where you join the live video session.</p><ul class="feature-list"><li>Join from the schedule without finding a separate meeting link.</li><li>Ask during the session or follow up in the program discussion.</li><li>Return to the resources your provider has shared.</li></ul>{link("See before, during, and after a session",u("/learning-experience/"))}</div>{classroom()}</div>','dark')
home+=section(head('Getting started','Choose a program.<br>Take it one step at a time.',desc='You can read public program pages first. Create an account when you are ready to book.')+steps()+f'<div class="actions">{btn("Explore programs",APP)}{link("How booking works",u("/how-it-works/"))}</div>')
home+=section(f'<div class="teach-block"><div class="teach-copy">{eyebrow("For providers")}<h2>Have a skill to share?<br><span class="serif">Give seekers a way to find it.</span></h2><p>Finding people to teach and managing the details can take as much effort as preparing the session.</p><p>Publish your programs where seekers can discover them. Keep enrollments, schedules, resources, and messages together, with live video built in for online sessions.</p><div class="actions">{btn("Explore becoming a provider",u("/teach/"))}</div></div>{img("people","People discussing their work together")}</div>')
home+=section(f'<div class="faq-grid"><div>{eyebrow("Before you decide")}<h2>A few practical<br>questions.</h2><p>Check the format, costs, and commitment before choosing your program.</p><div class="actions">{link("All questions and answers",u("/faq/"))}</div></div><div>{faq([FAQ[i] for i in [1,2,4,5,10]])}</div></div>')+closing()
page('/','Live Online & In-Person Programs | talent-share','Find live learning programs and providers you can ask questions. Compare the level, schedule, and requirements, then book online or in person.','live online and in-person programs',home)

# How it works
content=hero('How TalentShare works','How to book<br>and <span class="serif">attend a class.</span>','Start by checking whether a program fits your goal, level, and schedule. You can read the details before signing up, then book and attend through your account.','workshop','Learners working together in a pottery studio',btn('Browse programs',APP))
content+=section(head('Start here','Four steps to your first session.')+steps())
content+=section('<div class="split"><div>'+eyebrow('Before you book')+'<h2>Check the details<br><span class="serif">before you book.</span></h2><p>Read what the program covers, who it is for, and what you need to take part.</p><p>Read the teacher’s profile and portfolio, and look at any reviews. If a requirement is unclear, use the program’s message option to ask. You can clarify experience or equipment requirements before paying.</p></div><div class="panel"><span class="mini-label">Your pre-booking checklist</span><h3>What to check</h3><ul class="feature-list light"><li>Level, outcomes, and prior knowledge</li><li>Online or in person, with the location where relevant</li><li>Every session included in your selected program</li><li>Materials, preparation, and the checkout total</li><li>The current cancellation policy</li></ul></div></div>','wash')
content+=section('<div class="split"><div class="image-wrap">'+img('code','People working together on a laptop','image-block')+'</div><div>'+eyebrow('Attending a session')+'<h2>Find your session<br><span class="serif">on the program page.</span></h2><p>For live online learning, open the schedule in your program and join from there. Confirmed learners can enter from 15 minutes before the start. Video, screen sharing, and live chat are built into TalentShare.</p><p>For in-person learning, use the program details to plan where to be and what to bring. Your schedule and teacher announcements remain with the program, so check them before heading out.</p><div class="actions">'+link('Explore the classroom features',u('/learning-experience/'))+'</div></div></div>')
content+=section(head('After the session','Find your files and follow-up questions','Access shared resources and stay in touch with your teacher between sessions.')+'<div class="two-grid"><div class="panel"><h3>Resources and conversation</h3><p>Download files your teacher has shared. Continue a question in the class discussion, or use a private message for something individual. Repeating dates in a program series share their discussion, announcements, and file library.</p></div><div class="panel"><h3>Your next session and your review</h3><p>Your learning dashboard separates upcoming, in-progress, and completed programs. Find what is next without sorting through old bookings. After a completed enrollment, you can leave a review from the dashboard.</p></div></div>')+closing()
page('/how-it-works/','How TalentShare Works | Find, Book & Attend Live Classes','Learn how to choose a TalentShare program, check the details, book a date, and attend online or in person. Find your schedule, resources, and messages in one place.','how TalentShare works',content)

# Experience
content=hero('The program experience','Ask during the session.<br><span class="serif">Keep learning afterward.</span>','A question can come up while you are watching a demonstration or later when you practise. Your program gives you ways to ask, find resources, and prepare for the next session.',action=btn('Explore programs',APP))
content+=section(head('Before your session','Know where to be and what to bring.')+'<div class="two-grid"><div class="panel"><h3>Prepare from one program page</h3><p>Check the full schedule, requirements, and shared materials. Online sessions show a timezone. In-person programs include location details.</p></div><div class="panel"><h3>Keep up with changes</h3><p>Read your provider’s announcements for official updates. Session reminders help you keep track of what is coming up, and your dashboard points to the next session.</p></div></div>','wash')
content+=section(f'<div class="split"><div>{eyebrow("During an online session")}<h2>Ask about the step<br><span class="serif">you did not follow.</span></h2><p>The teacher starts the session from the program schedule. You join from the same place, with your camera, microphone, and session chat in the room.</p><p>Watch a shared screen in stage view or see the people in the session in a grid. You can switch your microphone and speaker, turn your camera off, or use fullscreen when you want to focus.</p><p>If the connection drops, the room tries to reconnect. Access is limited to the teacher and confirmed learners.</p></div>{classroom()}</div>','dark')
content+=section(comms(),'wash')
content+=section(head('After a session','Find your course files and schedule')+'<div class="two-grid"><div class="panel"><span class="mini-label">Course resources</span><h3>Download course materials</h3><p>Teachers can share documents, slides, spreadsheets, images, audio, video, and other supporting files. Confirmed learners download those resources from the program. For a repeating series, one shared library serves its different dates.</p><p>Open the program page to find the files your teacher has shared.</p></div><div class="panel"><span class="mini-label">Schedule & reminders</span><h3>Know what is coming up</h3><p>The program lists its sessions, and your dashboard shows the next one. Reminders are sent before class and when it starts. Program updates and cancellations have their own notifications.</p><p>Online schedules carry a timezone. Read it when choosing a program, especially if the teacher is in another part of the world.</p></div></div>')
content+=section('<div class="split"><div class="image-wrap">'+img('workshop','A group learning pottery together in person','image-block')+'</div><div>'+eyebrow('In person, too')+'<h2>Attend a class<br><span class="serif">in person.</span></h2><p>For a hands-on workshop, a shared space can be part of the experience. TalentShare also supports in-person programs, with a venue, address, and session schedule.</p><p>You can still access your booking, course files, teacher announcements, and class discussion from the program page. Check the materials list so you arrive with what you need.</p><div class="actions">'+link('Find a subject to explore',u('/subjects/'))+'</div></div></div>')
content+=section(head('Your account','Use one account to learn and teach')+'<div class="two-grid"><p>You do not need a second account to move between learning and teaching. Apply to become a teacher from the account you already use. Once approved, your learning and teaching dashboards keep the two kinds of activity organised.</p><p>Your learning view holds upcoming, in-progress, and completed programs. Your teaching view brings together programs, students, the calendar, messages, and reports. You can switch between the two views in the same account.</p></div>','pinkwash')+closing()
page('/learning-experience/','Live Learning Features & Online Classroom | TalentShare','Explore TalentShare’s built-in video classroom, announcements, class discussions, private messages, course files, and session reminders.','TalentShare live learning features',content)

# Provider conversion page
content=hero('For providers','You know your subject.<br><span class="serif">Help seekers find you.</span>','Turn your knowledge into a live program. Give seekers a clear way to see what you offer, book a place, and learn with you online or in person.','people','People sharing knowledge around a table',btn('Apply to become a provider',APP+'login')+link('How it works','#provider-process'))
content+=section(head('The work around teaching','A good program needs more<br>than a meeting link.',desc='You also need a way to reach seekers, explain the offer, and keep everything organised.')+'''<div class="problem-grid"><article><span class="problem-number">01</span><h3>Getting found</h3><p>Posting about your skill does not always help people understand what they can learn from you or how to book.</p></article><article><span class="problem-number">02</span><h3>Answering the same questions</h3><p>People need to know the level, schedule, materials, and price. Repeating those details in separate messages takes time.</p></article><article><span class="problem-number">03</span><h3>Keeping track of the program</h3><p>Enrollments, messages, files, and session links can end up in different places when you manage them separately.</p></article></div>''','wash')
content+=section('<div class="split"><div>'+eyebrow('Be part of a learning marketplace')+'<h2>Help seekers understand<br><span class="serif">what you can teach them.</span></h2><p>Your public profile puts your background, skills, languages, and portfolio alongside your programs. Seekers can search for programs or look for a provider by name.</p><p>Each program explains the outcomes, level, requirements, and schedule. This gives people useful information before they decide to book or send you a question.</p><p>After a completed enrollment, a seeker can leave a review. You can respond publicly, so future seekers can read both the feedback and your reply.</p></div><div class="panel"><span class="mini-label">Your public profile</span><h3>Show what is relevant to your subject</h3><ul class="feature-list light"><li>Professional and teaching experience</li><li>Skills, languages, and relevant qualifications</li><li>A portfolio with images, video, audio, or documents</li><li>Your programs and available seeker reviews</li></ul></div></div>')
content+=section('<div class="split" id="teaching-tools"><div>'+eyebrow('From idea to program')+'<h2>Explain the offer clearly.<br><span class="serif">Set the terms yourself.</span></h2><p>Choose the format, level, price, capacity, and schedule. Tell seekers what they will practise and what they need to bring. Save a draft and return to it when you are ready.</p><p>If writing the listing slows you down, describe the idea in a sentence. The optional AI writing assistant can suggest a title, description, and details supported by your prompt. Review and edit the result before publishing, or write everything yourself.</p><p>When you run a program again, add more start dates or duplicate it into a new draft. Repeating dates in a series share announcements, discussion, and one resource library.</p></div><div class="teacher-demo"><span class="demo-tag">Example program draft</span><div class="prompt-box">“A live online sketching program for beginners.”</div><div class="generated"><span class="mini-label">Review and edit before publishing</span><h3>Beginner Sketching Program Online</h3><p>Explain the exercises you will cover, the materials seekers need, and what they will practise.</p><span class="pill">Beginner</span><span class="pill">Online</span><span class="pill">Workshop format</span></div><p class="chat-hint">Illustrative draft. You choose the final details.</p></div></div>','wash')
content+=section(f'<div class="split"><div>{eyebrow("Run the program in one place")}<h2>Keep the admin<br><span class="serif">with the learning.</span></h2><p>Use the provider dashboard to manage programs, find enrolled seekers, check the calendar, and reply to messages. Reports show enrollments, reviews, and earnings for the dates you choose.</p><p>For an online session, start the built-in video room from the schedule. Share your screen, follow the session chat, and check seekers in. Upload supporting resources to the program so enrolled seekers can find them afterward.</p><ul class="feature-list"><li>Send official updates through announcements.</li><li>Keep group questions in program discussion.</li><li>Use private messages for individual questions.</li></ul>{link("Explore the program experience",u("/learning-experience/"))}</div>{classroom()}</div>','dark')
content+=section('<div id="provider-process">'+head('Becoming a provider','Start with your application.')+'<div class="steps provider-steps"><div class="step"><span class="number">01</span><h3>Tell us about your experience</h3><p>Apply from your account. Add your bio, background, skills, languages, and relevant qualifications or portfolio links.</p></div><div class="step"><span class="number">02</span><h3>Receive a review decision</h3><p>talent-share reviews provider applications. You are notified by email when your application is submitted and when a decision is made.</p></div><div class="step"><span class="number">03</span><h3>Prepare your first program</h3><p>Once approved, create your program, check the details, and publish it. Your profile and program help seekers decide whether to book.</p></div></div></div>')
content+=section(f'<div class="faq-grid"><div>{eyebrow("Before you apply")}<h2>Provider questions</h2><p>You can learn as a seeker and apply to become a provider with the same account.</p></div><div>{faq([FAQ[i] for i in [12,13,14,11]])}</div></div>','wash')
content+='<section class="closing"><div class="star-small" aria-hidden="true">✳</div><h2>Ready to share<br><span class="serif">what you know?</span></h2><p>Sign in to your account and start your provider application.</p><div class="actions">'+btn('Apply to become a provider',APP+'login')+'</div></section>'
page('/teach/','Become a Provider & Teach Live Programs | talent-share','Reach seekers with live online or in-person programs. Build your provider profile, set your program details, and manage enrollments and sessions with talent-share.','become a provider on talent-share',content)

FAQ.append(('What happens if the teacher cancels?', 'If the teacher cancels the program, learners receive a full refund to the original payment method. Refunds usually appear in 5 to 10 business days. TalentShare notifies you in the app and by email.'))

# Subjects and guides
content=hero('Explore subjects','Find a subject<br><span class="serif">you want to learn.</span>','Not sure where to start? Choose an interest, then use the guide to compare formats, check requirements, and decide what to ask a provider. Browse current programs in the app when you are ready.')
content+=section('<div class="filterbar" aria-label="Filter subject guides"><button data-filter="all" aria-pressed="true">All interests</button><button data-filter="creative" aria-pressed="false">Creative</button><button data-filter="professional" aria-pressed="false">Work & technology</button><button data-filter="everyday" aria-pressed="false">Everyday interests</button></div><p id="guide-count" class="sr-only" aria-live="polite">6 subject guides</p>'+category_cards())
content+=section(head('Choosing a program','Choose a program that fits your goals')+'<div class="two-grid"><div><h3>What would you like to be able to do?</h3><p style="margin-top:18px">Think about a specific skill you want to practise, such as cooking a dish or preparing a presentation. Use that goal to compare program descriptions, outcomes, and requirements.</p></div><div><h3>What kind of time can you give it?</h3><p style="margin-top:18px">A workshop, a course, and a consultation can ask for different kinds of commitment. Read the full schedule, not only the first date. Check whether you need equipment or practice time, and choose online or in person around the skill and your circumstances.</p></div></div>','wash')+closing()
page('/subjects/','Explore Learning Subjects & Class Guides | TalentShare','Explore guides to creative skills, technology, cooking, music, movement, and communication. Find out what to consider before choosing a live program.','live learning subject guides',content)
for s in SUBJECTS:
 content=hero('Subject guide',s['h1'],s['intro'],s['image'],s['alt'],btn('Explore current programs',APP),f'<a href="{u("/subjects/")}">Subjects</a><span>/</span>{s["name"]}')
 body=''.join(f'<h2>{h}</h2><p>{p}</p>' for h,p in s['body'])
 aside='<aside class="guide-aside"><span class="mini-label">Before you choose</span><h3>A few things to check</h3><ul>'+''.join(f'<li>{x}</li>' for x in s['check'])+'</ul><p class="chat-hint">Current programs, prices, and dates are available in the app.</p>'+btn('Browse the app',APP)+'</aside>'
 content+=section(f'<div class="guide-intro"><article class="reading">{body}</article>{aside}</div>')
 content+=section(f'<div class="faq-grid"><div>{eyebrow("Choosing your program")}<h2>Good questions<br>to ask.</h2></div><div>{faq(s["questions"])}</div></div>','wash')
 related=[x for x in SUBJECTS if x['slug']!=s['slug']][:2]
 content+=section(head('Keep exploring','Another interest in mind?')+'<div class="link-cards">'+''.join(f'<a class="link-card" href="{u("/subjects/"+x["slug"]+"/")}"><h3>{x["name"]}</h3><p>{x["tag"]}</p><span class="textlink">Read the guide {A}</span></a>' for x in related)+'</div>')+closing()
 page('/subjects/'+s['slug']+'/',s['h1']+' | TalentShare',f'Explore {s["name"].lower()} learning with TalentShare. Compare formats, check requirements, and learn what to ask before choosing a live program.',s['h1'].lower(),content)

# Trust
content=hero('Booking with confidence','What to know<br><span class="serif">before booking.</span>','A useful program page helps you decide before you pay. Here is what to look for, what stays private, and where to turn when you have a question.')
content+=section('<div class="reading"><h2>Start with the teacher</h2><p>Teacher applications are reviewed before approval. The public profile can show professional background, experience, education, certifications, skills, languages, and a portfolio. Look for the parts that relate to what you want to learn.</p><p>An approved application is a starting point for your research. Read the program itself and ask the teacher about any requirement that affects your decision.</p><h2>Use reviews for context</h2><p>Learners with completed enrollments can leave a rating and written review. Teachers can reply publicly. Read what the reviewer actually says about the experience, and consider whether they were looking for the same thing you are.</p><p>A program without reviews may still have a detailed description and teacher profile. Use those details and your own questions instead of treating missing feedback as a promise either way.</p><h2>Check the booking you have selected</h2><p>Read the delivery mode, level, selected date, full session schedule, and materials. When a program runs on several dates, your booking is for the selected run. That run may include more than one session. Review the schedule before continuing.</p><h2>See the total before you pay</h2><p>Checkout uses Stripe. The program price and service fee appear separately, along with the total. The receipt follows the same breakdown, and your payment history keeps the charge available to review. Card details stay with Stripe.</p><h2>Access to class spaces</h2><p>The video room, course files, announcements, and discussion are restricted to the teacher and confirmed learners. Direct messages are private conversations linked to a program. Use the appropriate space for the question you need to ask.</p><h2>Read the current cancellation policy</h2><p>You can request a cancellation within 24 hours of enrolling if the first session is still at least 24 hours away. The request is subject to platform approval. Check the current policy in the app before booking.</p><p>If the teacher cancels the program, learners receive a full refund to the original payment method. Refunds usually appear in 5 to 10 business days, and you are notified in the app and by email. Keep the program details and your receipt handy if you need support.</p><div class="note">Need help with a booking? Email <a href="mailto:support@talent-share.com">support@talent-share.com</a> with the program name or public program ID and a description of the issue. Never send your card details.</div><h2>Manage your account preferences</h2><p>Your settings include notification preferences and account controls. Email, push, and marketing preferences are separate. You can also find account deactivation and deletion options in settings.</p></div>')+closing()
page('/trust/','Booking, Payments & Teacher Profiles | TalentShare','Understand teacher profiles, reviews, program details, Stripe checkout, and private class spaces before booking a TalentShare program.','TalentShare booking and payments',content)
# FAQ
content=hero('Questions & answers','Questions about<br><span class="serif">TalentShare.</span>','A practical guide to learning, teaching, and finding your way around TalentShare.')
content+=section('<div class="reading"><label class="sr-only" for="faq-search">Search questions and answers</label><div class="searchbox"><input id="faq-search" type="search" placeholder="Search a question, like ‘online’ or ‘teach’" autocomplete="off"></div><p id="faq-count" aria-live="polite">17 answers</p>'+faq(FAQ)+'<p id="faq-empty" hidden>No answers match that search. Try a different word or contact support.</p><div class="note">Still need a hand? <a href="mailto:support@talent-share.com">Contact support</a> and tell us what you are trying to do.</div></div>')
page('/faq/','TalentShare FAQs | Learning, Teaching & Booking','Get answers about TalentShare programs, online classes, accounts, teacher applications, payments, resources, and reviews.','TalentShare FAQs',content)
# About
content=hero('About TalentShare','A place to<br><span class="serif">learn and teach.</span>','TalentShare connects people who want to learn with people who have something to teach. The exchange happens live, online or in person.','workshop','People learning pottery together',btn('Find something to learn',APP))
content+=section('<div class="reading"><h2>Learn directly from a teacher</h2><p>Learning with a teacher gives you the chance to ask questions and work through something you do not understand. You can watch a demonstration and practise during a live session.</p><p>TalentShare connects learners with teachers. Teachers create programs around what they know. Learners can read the details, choose a date, and attend a live session. Programs can take different forms, from a focused workshop or consultation to a course with several sessions.</p><h2>Online and in-person programs</h2><p>Online sessions run inside TalentShare. In-person programs bring people into the same physical space. Both have a program page that holds the schedule, booking details, resources, and conversations.</p><p>Announcements, private messages, class discussions, and course files are available through the program. You can check for updates and find shared materials without searching through separate email threads.</p><h2>Learn and teach with one account</h2><p>You might teach a skill you know well and learn something completely new the following week. The same account supports both. Learners can apply to teach, and approved teachers can keep learning through their own enrolled programs.</p><p>You can use TalentShare to learn, teach, or do both.</p><div class="actions">'+link('How the experience works',u('/learning-experience/'))+link('For providers',u('/teach/'))+'</div></div>')+closing()
page('/about/','About TalentShare | A Marketplace for Live Learning','TalentShare connects learners and teachers through live online and in-person programs. Learn about the marketplace and the experience built around each class.','about TalentShare',content)
# Generate metadata, robots, sitemap and content handoff
(OUT/'favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#703ad5"/><path d="M10 11h20v5h-7v15h-6V16h-7z" fill="#fff"/><circle cx="31" cy="29" r="3" fill="#e2f28c"/></svg>')
(OUT/'robots.txt').write_text(('User-agent: *\nAllow: /\nSitemap: '+ORIGIN+'/sitemap.xml\n') if PRODUCTION else 'User-agent: *\nDisallow: /\n')
(OUT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{ORIGIN}{p["path"]}</loc></url>' for p in pages)+'</urlset>')
(ROOT/'seo-map.json').write_text(json.dumps([{k:v for k,v in p.items() if k!='html'} for p in pages],indent=2))
try:
 from bs4 import BeautifulSoup
 output=['# talent-share website content\n','Editorial / Modernist with restrained neobrutalist accents. Existing TalentShare logo and violet brand family.\n','Static marketing and subject-guide content. Program listings, teacher profiles, prices, dates, enrollments, and account workflows remain at app.talent-share.com.\n']
 for p in pages:
  output+=[f'\n## {p["path"]}\n',f'Title tag: {p["title"]}\n\nMeta description: {p["description"]}\n\nPrimary keyword: {p["primary_keyword"]}\n']
  soup=BeautifulSoup(p['html'],'html.parser')
  for el in soup.select('h1,h2,h3,p,summary,li'):
   text=el.get_text(' ',strip=True)
   if text: output.append(('\n'+('#'*int(el.name[1])+ ' ' if el.name.startswith('h') else '')+text+'\n'))
 (ROOT.parent/'TalentShare-Website-Content.md').write_text('\n'.join(output))
except ImportError:pass
print(f'Built {len(pages)} static pages into {OUT}')
from html.parser import HTMLParser
class CopyParser(HTMLParser):
 def __init__(self):super().__init__();self.lines=[];self.parts=[];self.tag=None
 def handle_starttag(self,tag,attrs):
  if tag in ['h1','h2','h3','p','summary','li'] and self.tag is None:self.tag=tag;self.parts=[]
  if tag=='br' and self.tag:self.parts.append(' ')
 def handle_data(self,data):
  if self.tag:self.parts.append(data)
 def handle_endtag(self,tag):
  if tag==self.tag:
   text=''.join(self.parts).strip()
   if text:self.lines.append((('#'*int(tag[1])+' ') if tag.startswith('h') else ('- ' if tag=='li' else ''))+text)
   self.tag=None
copy=['# talent-share website content','Static marketing site, with live programs and account workflows at app.talent-share.com.','Visual direction: Editorial / Modernist with restrained neobrutalist accents. Existing TalentShare logo, violet and indigo, lilac, pink, warm white, and a small lime accent.']
for p in pages:
 parser=CopyParser();parser.feed(p['html'])
 copy.extend(['\n---\n',f'## Page: {p["path"]}',f'Title tag: {p["title"]}',f'Meta description: {p["description"]}',f'Primary keyword: {p["primary_keyword"]}',*parser.lines])
(ROOT.parent/'TalentShare-Website-Content.md').write_text('\n\n'.join(copy))
